name: Build CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python: [ "3.10" ]

    env:
      DISPLAY: ':99.0'

    steps:
    - name: Get repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Set up PyQt dependencies
      uses: tlambert03/setup-qt-libs@v1

    - name: Update pip and install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Freeze requirements
      run: pipenv requirements --dev > requirements.txt

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Test with pytest
      run: pytest -vvvv
